### ISSUE TITLE
Can't find "selected on 'Do you need additional entitlements?' page".

### ISSUE THREAD

**Issue by RanchenY** [lxdcn/NEPacketTunnelVPNDemo#10]
Hi,

When i create provision profiles, i can't find this page that ask me  'Do you need additional entitlements?' page?

How i fix it?

thank you.

**Comment by davlxd** [comment]
You may ignore and skip this, I was told that Entitlement from Apple for NetworkExtension is no longer needed, but I haven't tried.

**Comment by RanchenY** [comment]
yes, you are right.
now, xcode log is `Connected...`, but the 'vpn' didn't show on the iphone .

**Comment by davlxd** [comment]
It could be many reasons, mostly likely you missed one step or two during configuration. I suggest you go over `Prerequisites to build` and `Run` again to double check.

**Comment by RanchenY** [comment]
Hi, I've solved it. 
thank you ...
