### ISSUE TITLE
{NSLocalizedDescription=permission denied}

### ISSUE THREAD

**Issue by iambenmitchell** [lxdcn/NEPacketTunnelVPNDemo#12]
Go!
2018-05-11 17:37:48.404733+0100 NEPacketTunnelVPNDemo[4165:908595] [] -[NEConfigurationManager loadC:1673  Failed to load configurations: Error Domain=NEConfigurationErrorDomain Code=10 "permission denied" UserInfo={NSLocalizedDescription=permission denied}
2018-05-11 17:37:48.404952+0100 NEPacketTunnelVPNDemo[4165:908509] [] -[NETunnelProviderManager load:148  Failed to load the configuration: Error Domain=NEConfigurationErrorDomain Code=10 "permission denied" UserInfo={NSLocalizedDescription=permission denied}
Error Domain=NEVPNErrorDomain Code=5 "permission denied" UserInfo={NSLocalizedDescription=permission denied}
Error Domain=NEVPNErrorDomain Code=1 "(null)"

**Comment by davlxd** [comment]
Hi Ben

I have very little context about this error. All I can suggest now is go
over the Prerequisites to build on README.md and check if you miss any
steps.


Cheers

**Comment by iambenmitchell** [comment]
Hi, turns out it was because I didn't have a (Paid) developer apple ID, been meaning to get one for a while now. 

So I bought one

But now I am facing another issue, maybe you can help :) 
I'll get a log in a sec

**Comment by iambenmitchell** [comment]
Sorry, The last issue was fixed by turning the capabilities on and off, but now I face this:

VPN Status changed:
Invliad
Save successfully
Go!
VPN Status changed:
Disconnected...
VPN Status changed:
Connecting...
VPN Status changed:
Disconnected...

**Comment by iambenmitchell** [comment]
when I press connect: 

VPN Status changed:
Invliad
VPN Status changed:
Disconnected...
Save successfully
Go!
VPN Status changed:
Connecting...
VPN Status changed:
Disconnected...

Config: 

    // Hard code VPN configurations
    let tunnelBundleId = "tech.pyron.proxy.app1"
    let serverAddress = "p1.proxy.pyron.tech"
    let serverPort = "54345"
    let mtu = "1400"
    let ip = "10.8.0.0"
    let subnet = "255.255.255.0"
    let dns = "8.8.8.8,8.4.4.4"

**Comment by iambenmitchell** [comment]
terminal (remote ubuntu server)
root@p1 ~/test/simple-vpn-demo # ./vpn 
Execute `ifconfig tun0 10.8.0.1/16 mtu 1400 up`
Execute `sysctl -w net.ipv4.ip_forward=1`
net.ipv4.ip_forward = 1
Execute `iptables -t nat -A POSTROUTING -s 10.8.0.0/16 ! -d 10.8.0.0/16 -m comment --comment 'vpndemo' -j MASQUERADE`
Execute `iptables -A FORWARD -s 10.8.0.0/16 -m state --state RELATED,ESTABLISHED -j ACCEPT`
Execute `iptables -A FORWARD -d 10.8.0.0/16 -j ACCEPT`

**Comment by iambenmitchell** [comment]
**FIXED**
I used this git: https://github.com/lxdcn/NEPacketTunnelVPNDemo

Now it says connected, however theres no 'VPN' in the status bar.

**Comment by iambenmitchell** [comment]
and my ip is not changed

**Comment by iambenmitchell** [comment]
I fixed it by removing the <> where the IP was. IE <9.8.8.8.8> is now 9.8.8.8.8
