### ISSUE TITLE
More than one server?

### ISSUE THREAD

**Issue by iambenmitchell** [lxdcn/NEPacketTunnelVPNDemo#14]
Hello, I was wondering how I would add more than one server? IE have a 2nd button for server 2

**Comment by davlxd** [comment]
Hi I didn't check github during weekends and I am happy you solved those issues on your own.

I think you can achieve that by tweaking [ViewController.swft](https://github.com/lxdcn/NEPacketTunnelVPNDemo/blob/master/NEPacketTunnelVPNDemo/ViewController.swift). I haven't done that before but here are my advices:
  - Obviously you need one more [vpnManager](https://github.com/lxdcn/NEPacketTunnelVPNDemo/blob/master/NEPacketTunnelVPNDemo/ViewController.swift#L13)
  - When you save vpn config to system preferences, [initiate](https://github.com/lxdcn/NEPacketTunnelVPNDemo/blob/master/NEPacketTunnelVPNDemo/ViewController.swift#L53) another one, and [save it](https://github.com/lxdcn/NEPacketTunnelVPNDemo/blob/master/NEPacketTunnelVPNDemo/ViewController.swift#L57).
  - When you load vpn info back from system preferences, there will be multiple, as you can see in [here](https://github.com/lxdcn/NEPacketTunnelVPNDemo/blob/master/NEPacketTunnelVPNDemo/ViewController.swift#L33) I hardcoded to pick the first one, you need to alter this.
  - When you click the button, you need to find the correct vpnManager to [initiate connection](https://github.com/lxdcn/NEPacketTunnelVPNDemo/blob/master/NEPacketTunnelVPNDemo/ViewController.swift#L120)
  - Display logs for both vpnManagers in [here](https://github.com/lxdcn/NEPacketTunnelVPNDemo/blob/master/NEPacketTunnelVPNDemo/ViewController.swift#L84), and find a way to differentiate them.

Cheers

**Comment by iambenmitchell** [comment]
Oh... this is hella confusing lol, I think I will leave it until I drink enough coffee to be bothered to do It ;)

Thanks ;)
