### ISSUE TITLE
Select Ip

### ISSUE THREAD

**Issue by iambenmitchell** [lxdcn/NEPacketTunnelVPNDemo#15]
Hello, 

I have 3 IPs to choose from (all servers run on same port and same config)

I was wondering how I could create a list and choose from random, then pass the ip to let serverAddress = 

Again at random from 3 options.

**Comment by davlxd** [comment]
I don't think IP is runtimely alterable for vpn config, however you can
create 3 config with different port and randomly choose from when use click
connect.
Kinda like I replied in this thread:
https://github.com/lxdcn/NEPacketTunnelVPNDemo/issues/14

**Comment by iambenmitchell** [comment]
I duplicated the view controller.swift and changed the name on the new one to vpn2.swift.

Then I searched and replaced all connectButton with connectButton2.

I duplicated the button on main.storyboard so I had a 2nd one. Now what should I do?
