### ISSUE TITLE
Not connect to vpn server

### ISSUE THREAD

**Issue by aytunc** [lxdcn/NEPacketTunnelVPNDemo#2]
When I click on the button to establish a connection, I log in and the connection is not established. There is no problem on the server side.

xcode side
<img width="190" alt="ekran resmi 2017-04-30 19 09 05" src="https://cloud.githubusercontent.com/assets/10117849/25565863/883c9854-2dd8-11e7-925a-be84433f5e9b.png">

server side
<img width="835" alt="ekran resmi 2017-04-30 18 27 57" src="https://cloud.githubusercontent.com/assets/10117849/25565869/9ccab422-2dd8-11e7-8e4b-6eca40e069e2.png">

When i clicked on the button send the same log.
Go!
VPN Status changed:
Connecting...
VPN Status changed:
Disconnected...

The same when I tried the server off.
What is the problem ?

**Comment by cnkr** [comment]
When i clicked on the button send the same log.
Go!
VPN Status changed:
Connecting...
VPN Status changed:
Disconnected...

The same when I tried the server off.
What is the problem ?

**Comment by davlxd** [comment]
I replied your email.

**Comment by jerinjohnk** [comment]
#7 
Same error I am also getting. What is the fix for this? 
On server end once I run `sudo ./vpn` it ends up with 49 - 90 bytes being sent per second.
But once I deploy app it disconnects as soon as it connects.

**Comment by davlxd** [comment]
What do you mean?
Your server is receiving traffic without the client?

I have little context about your issue, but I think most of the issues around here got fixed by go over [here](https://github.com/lxdcn/NEPacketTunnelVPNDemo#prerequisites-to-build) again and make sure you didn't miss or misoperate any steps.

Good luck

**Comment by jerinjohnk** [comment]
@lxdcn even I was wondering the same, might be some network issue. But it was satisfying to see a spike in the frequency of traffic once i connect through iphone and stop in frequency of traffic once I disconnect
