### ISSUE TITLE
ios12显示 update required，不能连接vpn server，不知如何解决

### ISSUE THREAD

**Issue by zboya** [lxdcn/NEPacketTunnelVPNDemo#24]
非常感谢作者，自己copy你的项目后，ios跑起来显示`update required`  
## 环境
Swift版本：  
Apple Swift version 4.2 (swiftlang-1000.11.37.1 clang-1000.11.45.1)
Target: x86_64-apple-darwin17.7.0
 
Xcode版本：  
Version 10.0 (10A255)
 
iOS系统版本：12.0  (iPhone  6s)

### vpn显示
![wechatimg50](https://user-images.githubusercontent.com/13062034/46667357-0f148400-cbfc-11e8-97c9-cca4916ea931.jpeg)

### console日志
<img width="921" alt="screen shot 2018-10-09 at 7 43 46 pm" src="https://user-images.githubusercontent.com/13062034/46667257-b04f0a80-cbfb-11e8-929f-46f9e1aff1b0.png">

### vpn服务端
<img width="711" alt="screen shot 2018-10-09 at 7 45 33 pm" src="https://user-images.githubusercontent.com/13062034/46667317-eb513e00-cbfb-11e8-98a3-4459f04c9f7e.png">

**Comment by davlxd** [comment]
太客气了，给同行做点微不足道的贡献应该的。

这个错我倒是没遇到过，我看到NEPacketTunnelVPMDemoConfig 这个config的名儿应该是我取的，
然而VPN_demo这个名字应该是你取的吧，是给什么东西起的名字？

还有就是你确实按照这儿
https://github.com/lxdcn/NEPacketTunnelVPNDemo/blob/master/README.md#prerequisites-to-build
的流程一步步配置的吧，没遗漏什么。

**Comment by zboya** [comment]
> 太客气了，给同行做点微不足道的贡献应该的。 这个错我倒是没遇到过，我看到NEPacketTunnelVPMDemoConfig 这个config的名儿应该是我取的， 然而VPN_demo这个名字应该是你取的吧，是给什么东西起的名字？ 还有就是你确实按照这儿 https://github.com/lxdcn/NEPacketTunnelVPNDemo/blob/master/README.md#prerequisites-to-build 的流程一步步配置的吧，没遗漏什么。
> […](#)

我更改了项目名称，不更改项目名不知道为何签名一直报错，项目名字改为了VPN_demo，其他就是加了一些打印，你有ios12测试一下吗？谢谢

**Comment by davlxd** [comment]
项目名字被其他东西引用的很多，你要改的话全部都得改。

**Comment by zboya** [comment]
根据你的文档流程配置，可以跑了，但是我改了tcp以后，不会建立tcp连接，请问有试过tcp连接吗？

**Comment by davlxd** [comment]
一般情况下不会用TCP，因为tunnel对上层应用是透明的。
如果tunnel用TCP，上层应用会再建立一个TCP连接，这样开销大太大且没必要。

TCP连接我没试过，如果你要跑tcp，你得确定服务器端和iOS端都改了，服务器端创建fd
<https://github.com/lxdcn/simple-vpn-demo/blob/master/vpn.c#L166>，收发报文
<https://github.com/lxdcn/simple-vpn-demo/blob/master/vpn.c#L300>等等这些都要改，找一本UNIX
Network Programming翻翻参照改一改。
客户端主要就是这一行
<https://github.com/lxdcn/NEPacketTunnelVPNDemo/blob/master/NEPacketTunnelVPNDemoTunnel/PacketTunnelProvider.swift#L80>
从createUDPSession改称createTCPConnection。

祝顺利

**Comment by zboya** [comment]
嗯，非常感谢

**Comment by DaiYz** [comment]
@zboya 你好，我遇到了跟你一样的问题，请问是什么原因导致的呢
